from sqlalchemy import Column, Float, Integer, String, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

Base = declarative_base()

class Chiller(Base):
    __tablename__ = 'chillers'
    id = Column(String(100), primary_key=True, comment='Unique ID for the chiller')
    site_id = Column(String(255), nullable=False, comment='Foreign key to sites.id')
    chiller_num = Column(String(50), nullable=False, default='', comment='The numerical identifier of the chiller')
    serial_number = Column(String(255))
    model_number = Column(String(255))
    power_kW = Column(Float, comment='Nominal power of the chiller in kW')
    ton_of_refrigeration = Column(Float, comment='Nominal Ton of Refrigeration (TR) capacity')
    image_name = Column(String(255), default='chiller.png', comment='Filename for the chiller static image')
    created_at = Column(DateTime, default=datetime.now, comment='Timestamp when the chiller record was created')
    chiller_type = Column(String(50), default='default_type')

    datas = relationship("ChillerData", back_populates="chiller")

class ChillerData(Base):
    __tablename__ = 'chiller_datas'
    id = Column(Integer, primary_key=True, autoincrement=True, comment='Unique identifier for each historical data record.')
    timestamp = Column(DateTime, nullable=False, comment='The timestamp of the data point.')
    chiller_id = Column(String(100), ForeignKey('chillers.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False, comment='Foreign key to chillers.id.')
    evap_lwt = Column(Float, comment='Evaporator Leaving Water Temperature (C)')
    evap_rwt = Column(Float, comment='Evaporator Returning Water Temperature (C)')
    evap_pressure = Column(Float, comment='Evaporator pressure (psi)')
    evap_satur_temp = Column(Float)
    evap_std = Column(Float)
    evap_refri_lvl = Column(Float)
    cond_rwt = Column(Float)
    cond_lwt = Column(Float)
    cond_pressure = Column(Float)
    cond_satur_temp = Column(Float)
    cond_std = Column(Float)
    cond_refri_lvl = Column(Float)
    cond_refri_lvl_sp = Column(Float)
    drop_leg_refri_temp = Column(Float)
    oil_pressure_diff = Column(Float)
    oil_sump_temp = Column(Float)
    discharge_temp = Column(Float)
    discharge_superheat = Column(Float)
    oil_sump_pressure = Column(Float)
    oil_pump_pressure = Column(Float)
    fla = Column(Float)
    input_power = Column(Float)
    input_kwh = Column(Float)
    operating_hour = Column(Float)
    number_of_start = Column(Integer)
    act_current_limit = Column(Float)
    vsd_out_voltage = Column(Float)
    vsd_out_freq = Column(Float)
    vsd_ph_a_current = Column(Float)
    vsd_ph_b_current = Column(Float)
    vsd_ph_c_current = Column(Float)
    mtr_wind_ph_a_temp = Column(Float)
    mtr_wind_ph_b_temp = Column(Float)
    mtr_wind_ph_c_temp = Column(Float)
    status = Column(Integer)
    warning = Column(Integer)
    alarm = Column(Integer)
    safety_fault = Column(Integer)
    cycling_fault = Column(Integer)
    warning_fault = Column(Integer)
    operating_code = Column(Integer)
    liq_line_solenoid = Column(Integer)
    ch_liq_pump_sts = Column(Integer)
    panel_stop_switch_sts = Column(Integer)
    ch_liq_flow_switch = Column(Integer)
    cond_liq_flow_switch = Column(Integer)
    cond_liq_pump_sts = Column(Integer)
    ch1_evap_rwt_fahrenheit = Column(Float)
    ch1_evap_lwt_fahrenheit = Column(Float)
    ch2_evap_rwt_fahrenheit = Column(Float)
    ch2_evap_lwt_fahrenheit = Column(Float)
    ch3_evap_rwt_fahrenheit = Column(Float)
    ch3_evap_lwt_fahrenheit = Column(Float)
    ch4_evap_rwt_fahrenheit = Column(Float)
    ch4_evap_lwt_fahrenheit = Column(Float)
    leav_ch_liq_sp = Column(Float)
    evap_rwt_fahrenheit = Column(Float)
    evap_lwt_fahrenheit = Column(Float)
    VSD_Input_Power = Column(Float)
    VSD_Input_KWH = Column(Float)
    Evap_Refri_Temp = Column(Float)
    Vsd_In_Amb_Temp = Column(Float)
    Sys1_Disch_Temp = Column(Float)
    Sys1_Oil_Press = Column(Float)
    Sys1_Evap_Press = Column(Float)
    Sys1_Disch_Press = Column(Float)
    Sys1_Comp_FLA = Column(Float)
    Sys1_Run_Hour = Column(Float)
    Sys2_Oil_Press = Column(Float)
    Sys2_Suct_Press = Column(Float)
    Sys2_Disch_Press = Column(Float)
    Sys2_Comp_FLA = Column(Float)
    Sys2_Run_Hour = Column(Float)
    Chiller_Run = Column(Integer)
    Chiller_Alarm = Column(Integer)
    Fault_Code = Column(Integer)
    Sys1_Suct_Temp = Column(Float)
    Amb_Air_Temp = Column(Float)
    Sys1_Suct_Superheat = Column(Float)
    Sys1_EEV_Out_Pct = Column(Float)
    Sys1_Com1_Hour = Column(Float)
    Sys1_Com2_Hour = Column(Float)
    Sys1_Com3_Hour = Column(Float)
    Sys2_Com1_Hour = Column(Float)
    Sys2_Com2_Hour = Column(Float)
    Sys2_Com3_Hour = Column(Float)
    Sys1_Com1_Run = Column(Integer)
    Sys1_Com2_Run = Column(Integer)
    Sys1_Com3_Run = Column(Integer)
    Sys2_Com1_Run = Column(Integer)
    Sys2_Com2_Run = Column(Integer)
    Sys2_Com3_Run = Column(Integer)
    Sys2_Suct_Temp = Column(Float)
    Sys2_Suct_Superheat = Column(Float)
    Sys2_EEV_Out_Pct = Column(Float)
    Sys1_Disch_Superheat = Column(Float)
    Sys2_Disch_Temp = Column(Float)
    Sys2_Disch_Superheat = Column(Float)
    Sys1_Fault_Code = Column(Integer)
    Sys2_Fault_Code = Column(Integer)
    Sys1_Cond_Temp = Column(Float)
    Out_Amb_Temp = Column(Float)
    Sys1_Eductor_Temp = Column(Float)
    Sys2_Eductor_Temp = Column(Float)
    Sys1_Alarm = Column(Integer)
    Sys2_Alarm = Column(Integer)
    Sys2_Cond_Temp = Column(Float)
    Sys1_Motor_Temp_1 = Column(Float)
    Sys1_Motor_Temp_2 = Column(Float)
    Sys1_Motor_Temp_3 = Column(Float)
    Sys2_Motor_Temp_1 = Column(Float)
    Sys2_Motor_Temp_2 = Column(Float)
    Sys2_Motor_Temp_3 = Column(Float)
    Sys1_Warning_Code = Column(Integer)
    Sys2_Warning_Code = Column(Integer)
    Sys1_Fan_Power = Column(Float)
    Sys1_Comp_Power = Column(Float)
    Sys2_Fan_Power = Column(Float)
    Sys2_Comp_Power = Column(Float)
    Motor_Ph_A_Current = Column(Float)
    Motor_Ph_B_Current = Column(Float)
    Motor_Ph_C_Current = Column(Float)
    Motor_Ph_A_Voltage = Column(Float)
    Motor_Ph_B_Voltage = Column(Float)
    Motor_Ph_C_Voltage = Column(Float)
    Seal_Press_Diff = Column(Float)
    Filter_Diff_Press = Column(Float)
    Output_Voltage = Column(Float)
    Evap_DT = Column(Float)
    Cond_DT = Column(Float)
    Approach_Evap = Column(Float)
    Approach_Cond = Column(Float)
    Cooling_Capacity = Column(Float)
    efficiency = Column(Float)
    COP = Column(Float)
    EER = Column(Float)

    
    chiller = relationship("Chiller", back_populates="datas")